//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probasem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вход сотрудника.
    /// </summary>
    // *** Start programmer edit section *** (ВходСотрудника CustomAttributes)

    // *** End programmer edit section *** (ВходСотрудника CustomAttributes)
    [AutoAltered()]
    [Caption("Вход сотрудника")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВходСотрудникаE", new string[] {
            "РегКартСотруд.Сотрудник as \'ФИО\'",
            "РегКартСотруд.Сотрудник.Должность.Должность"})]
    public class ВходСотрудника : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Probasem.РегКартСотруд fРегКартСотруд;
        
        private IIS.Probasem.РегистрацВход fРегистрацВход;
        
        // *** Start programmer edit section *** (ВходСотрудника CustomMembers)

        // *** End programmer edit section *** (ВходСотрудника CustomMembers)

        
        /// <summary>
        /// Вход сотрудника.
        /// </summary>
        // *** Start programmer edit section *** (ВходСотрудника.РегКартСотруд CustomAttributes)

        // *** End programmer edit section *** (ВходСотрудника.РегКартСотруд CustomAttributes)
        [PropertyStorage(new string[] {
                "РегКартСотруд"})]
        [NotNull()]
        public virtual IIS.Probasem.РегКартСотруд РегКартСотруд
        {
            get
            {
                // *** Start programmer edit section *** (ВходСотрудника.РегКартСотруд Get start)

                // *** End programmer edit section *** (ВходСотрудника.РегКартСотруд Get start)
                IIS.Probasem.РегКартСотруд result = this.fРегКартСотруд;
                // *** Start programmer edit section *** (ВходСотрудника.РегКартСотруд Get end)

                // *** End programmer edit section *** (ВходСотрудника.РегКартСотруд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходСотрудника.РегКартСотруд Set start)

                // *** End programmer edit section *** (ВходСотрудника.РегКартСотруд Set start)
                this.fРегКартСотруд = value;
                // *** Start programmer edit section *** (ВходСотрудника.РегКартСотруд Set end)

                // *** End programmer edit section *** (ВходСотрудника.РегКартСотруд Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probasem.РегистрацВход.
        /// </summary>
        // *** Start programmer edit section *** (ВходСотрудника.РегистрацВход CustomAttributes)

        // *** End programmer edit section *** (ВходСотрудника.РегистрацВход CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РегистрацВход"})]
        public virtual IIS.Probasem.РегистрацВход РегистрацВход
        {
            get
            {
                // *** Start programmer edit section *** (ВходСотрудника.РегистрацВход Get start)

                // *** End programmer edit section *** (ВходСотрудника.РегистрацВход Get start)
                IIS.Probasem.РегистрацВход result = this.fРегистрацВход;
                // *** Start programmer edit section *** (ВходСотрудника.РегистрацВход Get end)

                // *** End programmer edit section *** (ВходСотрудника.РегистрацВход Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходСотрудника.РегистрацВход Set start)

                // *** End programmer edit section *** (ВходСотрудника.РегистрацВход Set start)
                this.fРегистрацВход = value;
                // *** Start programmer edit section *** (ВходСотрудника.РегистрацВход Set end)

                // *** End programmer edit section *** (ВходСотрудника.РегистрацВход Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВходСотрудникаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходСотрудникаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходСотрудникаE", typeof(IIS.Probasem.ВходСотрудника));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВходСотрудника.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВходСотрудника CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВходСотрудника CustomAttributes)
    public class DetailArrayOfВходСотрудника : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probasem.DetailArrayOfВходСотрудника members)

        // *** End programmer edit section *** (IIS.Probasem.DetailArrayOfВходСотрудника members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВходСотрудника by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВходСотрудника.
        /// </summary>
        public DetailArrayOfВходСотрудника(IIS.Probasem.РегистрацВход fРегистрацВход) : 
                base(typeof(ВходСотрудника), ((ICSSoft.STORMNET.DataObject)(fРегистрацВход)))
        {
        }
        
        public IIS.Probasem.ВходСотрудника this[int index]
        {
            get
            {
                return ((IIS.Probasem.ВходСотрудника)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probasem.ВходСотрудника dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
