//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probasem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рег карт сотруд.
    /// </summary>
    // *** Start programmer edit section *** (РегКартСотруд CustomAttributes)

    // *** End programmer edit section *** (РегКартСотруд CustomAttributes)
    [AutoAltered()]
    [Caption("Регистрация карт сотрудников")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегКартСотрудE", new string[] {
            "Дата as \'Дата\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.ФИО as \'ФИО\'",
            "Карта as \'Карта\'",
            "Карта.КодКарты as \'Код карты\'"}, Hidden=new string[] {
            "Сотрудник.ФИО",
            "Карта.КодКарты"})]
    [MasterViewDefineAttribute("РегКартСотрудE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("РегКартСотрудE", "Карта", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [View("РегКартСотрудL", new string[] {
            "Дата as \'Дата\'",
            "Сотрудник.ФИО as \'ФИО\'",
            "Карта.КодКарты as \'Код карты\'"})]
    public class РегКартСотруд : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Probasem.Сотрудник fСотрудник;
        
        private IIS.Probasem.Карта fКарта;
        
        // *** Start programmer edit section *** (РегКартСотруд CustomMembers)

        // *** End programmer edit section *** (РегКартСотруд CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РегКартСотруд.Дата CustomAttributes)

        // *** End programmer edit section *** (РегКартСотруд.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РегКартСотруд.Дата Get start)

                // *** End programmer edit section *** (РегКартСотруд.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РегКартСотруд.Дата Get end)

                // *** End programmer edit section *** (РегКартСотруд.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегКартСотруд.Дата Set start)

                // *** End programmer edit section *** (РегКартСотруд.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РегКартСотруд.Дата Set end)

                // *** End programmer edit section *** (РегКартСотруд.Дата Set end)
            }
        }
        
        /// <summary>
        /// Рег карт сотруд.
        /// </summary>
        // *** Start programmer edit section *** (РегКартСотруд.Карта CustomAttributes)

        // *** End programmer edit section *** (РегКартСотруд.Карта CustomAttributes)
        [PropertyStorage(new string[] {
                "Карта"})]
        [NotNull()]
        public virtual IIS.Probasem.Карта Карта
        {
            get
            {
                // *** Start programmer edit section *** (РегКартСотруд.Карта Get start)

                // *** End programmer edit section *** (РегКартСотруд.Карта Get start)
                IIS.Probasem.Карта result = this.fКарта;
                // *** Start programmer edit section *** (РегКартСотруд.Карта Get end)

                // *** End programmer edit section *** (РегКартСотруд.Карта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегКартСотруд.Карта Set start)

                // *** End programmer edit section *** (РегКартСотруд.Карта Set start)
                this.fКарта = value;
                // *** Start programmer edit section *** (РегКартСотруд.Карта Set end)

                // *** End programmer edit section *** (РегКартСотруд.Карта Set end)
            }
        }
        
        /// <summary>
        /// Рег карт сотруд.
        /// </summary>
        // *** Start programmer edit section *** (РегКартСотруд.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (РегКартСотруд.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Probasem.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (РегКартСотруд.Сотрудник Get start)

                // *** End programmer edit section *** (РегКартСотруд.Сотрудник Get start)
                IIS.Probasem.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (РегКартСотруд.Сотрудник Get end)

                // *** End programmer edit section *** (РегКартСотруд.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегКартСотруд.Сотрудник Set start)

                // *** End programmer edit section *** (РегКартСотруд.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (РегКартСотруд.Сотрудник Set end)

                // *** End programmer edit section *** (РегКартСотруд.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегКартСотрудE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегКартСотрудE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегКартСотрудE", typeof(IIS.Probasem.РегКартСотруд));
                }
            }
            
            /// <summary>
            /// "РегКартСотрудL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегКартСотрудL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегКартСотрудL", typeof(IIS.Probasem.РегКартСотруд));
                }
            }
        }
    }
}
