//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probasem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регис карт гостей.
    /// </summary>
    // *** Start programmer edit section *** (РегисКартГостей CustomAttributes)

    // *** End programmer edit section *** (РегисКартГостей CustomAttributes)
    [AutoAltered()]
    [Caption("Регистрация карт гостей")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегисКартГостейE", new string[] {
            "Дата as \'Дата\'",
            "Гость as \'Гость\'",
            "Гость.ФИО as \'ФИО\'",
            "Комната as \'Комната\'",
            "Комната.Номер as \'Номер\'",
            "Карта as \'Карта\'",
            "Карта.КодКарты as \'Код карты\'"}, Hidden=new string[] {
            "Гость.ФИО",
            "Комната.Номер",
            "Карта.КодКарты"})]
    [MasterViewDefineAttribute("РегисКартГостейE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("РегисКартГостейE", "Комната", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("РегисКартГостейE", "Карта", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [View("РегисКартГостейL", new string[] {
            "Дата as \'Дата\'",
            "Гость.ФИО as \'ФИО\'",
            "Комната.Номер as \'Номер\'",
            "Карта.КодКарты as \'Код карты\'"})]
    public class РегисКартГостей : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Probasem.Карта fКарта;
        
        private IIS.Probasem.Комната fКомната;
        
        private IIS.Probasem.Гость fГость;
        
        // *** Start programmer edit section *** (РегисКартГостей CustomMembers)

        // *** End programmer edit section *** (РегисКартГостей CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РегисКартГостей.Дата CustomAttributes)

        // *** End programmer edit section *** (РегисКартГостей.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РегисКартГостей.Дата Get start)

                // *** End programmer edit section *** (РегисКартГостей.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РегисКартГостей.Дата Get end)

                // *** End programmer edit section *** (РегисКартГостей.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегисКартГостей.Дата Set start)

                // *** End programmer edit section *** (РегисКартГостей.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РегисКартГостей.Дата Set end)

                // *** End programmer edit section *** (РегисКартГостей.Дата Set end)
            }
        }
        
        /// <summary>
        /// Регис карт гостей.
        /// </summary>
        // *** Start programmer edit section *** (РегисКартГостей.Гость CustomAttributes)

        // *** End programmer edit section *** (РегисКартГостей.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Probasem.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (РегисКартГостей.Гость Get start)

                // *** End programmer edit section *** (РегисКартГостей.Гость Get start)
                IIS.Probasem.Гость result = this.fГость;
                // *** Start programmer edit section *** (РегисКартГостей.Гость Get end)

                // *** End programmer edit section *** (РегисКартГостей.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегисКартГостей.Гость Set start)

                // *** End programmer edit section *** (РегисКартГостей.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (РегисКартГостей.Гость Set end)

                // *** End programmer edit section *** (РегисКартГостей.Гость Set end)
            }
        }
        
        /// <summary>
        /// Регис карт гостей.
        /// </summary>
        // *** Start programmer edit section *** (РегисКартГостей.Карта CustomAttributes)

        // *** End programmer edit section *** (РегисКартГостей.Карта CustomAttributes)
        [PropertyStorage(new string[] {
                "Карта"})]
        [NotNull()]
        public virtual IIS.Probasem.Карта Карта
        {
            get
            {
                // *** Start programmer edit section *** (РегисКартГостей.Карта Get start)

                // *** End programmer edit section *** (РегисКартГостей.Карта Get start)
                IIS.Probasem.Карта result = this.fКарта;
                // *** Start programmer edit section *** (РегисКартГостей.Карта Get end)

                // *** End programmer edit section *** (РегисКартГостей.Карта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегисКартГостей.Карта Set start)

                // *** End programmer edit section *** (РегисКартГостей.Карта Set start)
                this.fКарта = value;
                // *** Start programmer edit section *** (РегисКартГостей.Карта Set end)

                // *** End programmer edit section *** (РегисКартГостей.Карта Set end)
            }
        }
        
        /// <summary>
        /// Регис карт гостей.
        /// </summary>
        // *** Start programmer edit section *** (РегисКартГостей.Комната CustomAttributes)

        // *** End programmer edit section *** (РегисКартГостей.Комната CustomAttributes)
        [PropertyStorage(new string[] {
                "Комната"})]
        [NotNull()]
        public virtual IIS.Probasem.Комната Комната
        {
            get
            {
                // *** Start programmer edit section *** (РегисКартГостей.Комната Get start)

                // *** End programmer edit section *** (РегисКартГостей.Комната Get start)
                IIS.Probasem.Комната result = this.fКомната;
                // *** Start programmer edit section *** (РегисКартГостей.Комната Get end)

                // *** End programmer edit section *** (РегисКартГостей.Комната Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегисКартГостей.Комната Set start)

                // *** End programmer edit section *** (РегисКартГостей.Комната Set start)
                this.fКомната = value;
                // *** Start programmer edit section *** (РегисКартГостей.Комната Set end)

                // *** End programmer edit section *** (РегисКартГостей.Комната Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегисКартГостейE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегисКартГостейE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегисКартГостейE", typeof(IIS.Probasem.РегисКартГостей));
                }
            }
            
            /// <summary>
            /// "РегисКартГостейL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегисКартГостейL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегисКартГостейL", typeof(IIS.Probasem.РегисКартГостей));
                }
            }
        }
    }
}
