//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probasem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистрац вход.
    /// </summary>
    // *** Start programmer edit section *** (РегистрацВход CustomAttributes)

    // *** End programmer edit section *** (РегистрацВход CustomAttributes)
    [AutoAltered()]
    [Caption("Регистрация входа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрацВходE", new string[] {
            "Дата as \'Дата\'",
            "Комната as \'Комната\'",
            "Комната.Номер as \'Номер\'"}, Hidden=new string[] {
            "Комната.Номер"})]
    [AssociatedDetailViewAttribute("РегистрацВходE", "ВходСотрудника", "ВходСотрудникаE", true, "", "Вход сотрудника", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("РегистрацВходE", "ВходГостя", "ВходГостяE", true, "", "Вход гостя", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РегистрацВходE", "Комната", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("РегистрацВходL", new string[] {
            "Дата as \'Дата\'",
            "Комната.Номер as \'Номер\'"})]
    public class РегистрацВход : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Probasem.Комната fКомната;
        
        private IIS.Probasem.DetailArrayOfВходГостя fВходГостя;
        
        private IIS.Probasem.DetailArrayOfВходСотрудника fВходСотрудника;
        
        // *** Start programmer edit section *** (РегистрацВход CustomMembers)

        // *** End programmer edit section *** (РегистрацВход CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацВход.Дата CustomAttributes)

        // *** End programmer edit section *** (РегистрацВход.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацВход.Дата Get start)

                // *** End programmer edit section *** (РегистрацВход.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РегистрацВход.Дата Get end)

                // *** End programmer edit section *** (РегистрацВход.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацВход.Дата Set start)

                // *** End programmer edit section *** (РегистрацВход.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РегистрацВход.Дата Set end)

                // *** End programmer edit section *** (РегистрацВход.Дата Set end)
            }
        }
        
        /// <summary>
        /// Регистрац вход.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацВход.Комната CustomAttributes)

        // *** End programmer edit section *** (РегистрацВход.Комната CustomAttributes)
        [PropertyStorage(new string[] {
                "Комната"})]
        [NotNull()]
        public virtual IIS.Probasem.Комната Комната
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацВход.Комната Get start)

                // *** End programmer edit section *** (РегистрацВход.Комната Get start)
                IIS.Probasem.Комната result = this.fКомната;
                // *** Start programmer edit section *** (РегистрацВход.Комната Get end)

                // *** End programmer edit section *** (РегистрацВход.Комната Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацВход.Комната Set start)

                // *** End programmer edit section *** (РегистрацВход.Комната Set start)
                this.fКомната = value;
                // *** Start programmer edit section *** (РегистрацВход.Комната Set end)

                // *** End programmer edit section *** (РегистрацВход.Комната Set end)
            }
        }
        
        /// <summary>
        /// Регистрац вход.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацВход.ВходГостя CustomAttributes)

        // *** End programmer edit section *** (РегистрацВход.ВходГостя CustomAttributes)
        public virtual IIS.Probasem.DetailArrayOfВходГостя ВходГостя
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацВход.ВходГостя Get start)

                // *** End programmer edit section *** (РегистрацВход.ВходГостя Get start)
                if ((this.fВходГостя == null))
                {
                    this.fВходГостя = new IIS.Probasem.DetailArrayOfВходГостя(this);
                }
                IIS.Probasem.DetailArrayOfВходГостя result = this.fВходГостя;
                // *** Start programmer edit section *** (РегистрацВход.ВходГостя Get end)

                // *** End programmer edit section *** (РегистрацВход.ВходГостя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацВход.ВходГостя Set start)

                // *** End programmer edit section *** (РегистрацВход.ВходГостя Set start)
                this.fВходГостя = value;
                // *** Start programmer edit section *** (РегистрацВход.ВходГостя Set end)

                // *** End programmer edit section *** (РегистрацВход.ВходГостя Set end)
            }
        }
        
        /// <summary>
        /// Регистрац вход.
        /// </summary>
        // *** Start programmer edit section *** (РегистрацВход.ВходСотрудника CustomAttributes)

        // *** End programmer edit section *** (РегистрацВход.ВходСотрудника CustomAttributes)
        public virtual IIS.Probasem.DetailArrayOfВходСотрудника ВходСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (РегистрацВход.ВходСотрудника Get start)

                // *** End programmer edit section *** (РегистрацВход.ВходСотрудника Get start)
                if ((this.fВходСотрудника == null))
                {
                    this.fВходСотрудника = new IIS.Probasem.DetailArrayOfВходСотрудника(this);
                }
                IIS.Probasem.DetailArrayOfВходСотрудника result = this.fВходСотрудника;
                // *** Start programmer edit section *** (РегистрацВход.ВходСотрудника Get end)

                // *** End programmer edit section *** (РегистрацВход.ВходСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрацВход.ВходСотрудника Set start)

                // *** End programmer edit section *** (РегистрацВход.ВходСотрудника Set start)
                this.fВходСотрудника = value;
                // *** Start programmer edit section *** (РегистрацВход.ВходСотрудника Set end)

                // *** End programmer edit section *** (РегистрацВход.ВходСотрудника Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрацВходE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрацВходE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрацВходE", typeof(IIS.Probasem.РегистрацВход));
                }
            }
            
            /// <summary>
            /// "РегистрацВходL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрацВходL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрацВходL", typeof(IIS.Probasem.РегистрацВход));
                }
            }
        }
    }
}
